### ISSUE TITLE
BookComparator.java Issue

### ISSUE THREAD

**Issue by Aregluss** [L-S-Farlee/JavaLibrary#8]
Good job on actually writing this, lots of people wouldn't go to this length. I do have one suggestion though.

Instead of making a comparator in a separate class you can make it a part of Book.java

Refer to this [GeeksForGeeks example](https://www.geeksforgeeks.org/comparator-interface-java/), it'd help you see what I mean. (Fairly short)

Keep in mind by putting it in the Book.java you will possibly have to make some other changes where you use it. So we can leave this to later, but something worth doing.

Maybe for practice add a new comparator to Book.java, this current one compares based on authors. I encourage you add one to Book.java that compares based on title of the book.

Lmk in the comments here if you want to talk further about this.

**Comment by L-S-Farlee** [comment]
[I implemented two comparators for sorting](https://github.com/L-S-Farlee/JavaLibrary/blob/7c69dc956cee07ec05420e7d0c7dab5e40edf99a/src/application/LibraryData.java#L205) (by author and by title), also moved them to the LibraryData class and made them inner classes. Deleted the BookComparator class. Good suggestion!

Fixed in #15.
